// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqavmciyewkhurnblhom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxYXZtY2l5ZXdraHVybmJsaG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzA4MTIsImV4cCI6MjA3Mzk0NjgxMn0.__9N9cnJu3JF6hUjo_xqx33u7g8K-cxVQwh1ziaQnOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});